---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# R package: `wei.series.md.c1.c2.c3`

A likelihood model for series systems with Weibull component lifetimes.
Accounts for right-censoring and candidate sets indicative of masked failure
causes. 

<!-- badges: start -->
<!-- badges: end -->

## Installation

You can install the development version of wei.series.md.c1.c2.c3 from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("queelius/wei.series.md.c1.c2.c3")
```

```{r}
library(algebraic.dist)
library(algebraic.mle)
library(wei.series.md.c1.c2.c3)
```


```{r}
# fit the model
fit <- mle_numerical(mle_lbfgsb_wei_series_md_c1_c2_c3(
  df = guo_weibull_series_md$data,
  theta0 = c(1,1,1,1,1,1),
  control = list(
    maxit = 1000L,
    parscale = c(1, 1000, 1, 1000, 1, 1000))))

cbind(confint(fit),
  "fit" = params(fit),
  "guo mle" = guo_weibull_series_md$mle)

# log-likelihood
c("guo log-like" = guo_weibull_series_md$loglike, "fit log-like" = loglik_val(fit))
```

We see that they are approximately the same.
```{r}
fit.shapes <- round(params(fit)[seq(1, length(params(fit)), 2)],digits=4)
fit.scales <- round(params(fit)[seq(2, length(params(fit)), 2)],digits=4)

wei_series_cause(1L:5L, shapes = alex_weibull_series$shapes,
  scales = alex_weibull_series$scales)

s <- 0
for (i in 1:length(alex_weibull_series$shapes)) {
  s <- s + wei_mttf(shape = alex_weibull_series$shapes[i],
           scale = alex_weibull_series$scales[i])
  cat("MTTF component ", i, ": ", wei_mttf(shape = alex_weibull_series$shapes[i],
           scale = alex_weibull_series$scales[i]), "\n")
}

wei_series_mttf(shapes = alex_weibull_series$shapes,
  scales = alex_weibull_series$scales)
```

